### ISSUE TITLE
pitch game freeze

### ISSUE THREAD

**Issue by outer-space** [publicscience/the_founder#33]
sometimes the pitch game freezes when a lobbed pitch splinters into blue balls that don't come into contact with the lower edge of the screen. if the blue balls exit by the sides of the screen only, no new red ball appears, even if there are pitches left, and the only option is to close the app (hitting the 'back' button doesn't do anything, and there's no way to x out of the minigame)

// in a similar vein, when you get to the multiplex office campus, the new product game takes 5eva and there's not way to x out but to close the app (or let it run out)

**Comment by ftzeng** [comment]
see #31
